version: 2.1
 
command:
  print_pipeline_id:
    step:
      - run: echo $CIRCLE_WORKFLOW_ID 
jobs:
  print_id:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - print_pipeline_id
    
workflow:
  my_workflow:
    - print_id
